### ISSUE TITLE
English Menus ?

### ISSUE THREAD

**Issue by privaterra** [systopia/de.systopia.committees#6]
Are the menus for this extension just in German, or in English as well? I ask, as I'd be keen to test it out and see how it might be useful for US congressional related data that I have in CiviCRM. thanks!

**Comment by bjendres** [comment]
Hi @privaterra. 

> Are the menus for this extension just in German, or in English as well? 

They should already be English anyway, but the UI is a very small part of the system. Most things are happening in the importer and syncer modules, and the ones included tend to be very specific - so those might have German names. If that doesn't answer your question, maybe you could post a screenshot of what you're referring to.

> I'd be keen to test it out and see how it might be useful for US congressional related data that I have in CiviCRM

In theory it should, but since your input data is probably in a different format than the ones we know, somebody would have to create a least a new importer. Let me know if you want to have a brief chat about it. I trust you read the the documentaton here https://github.com/systopia/de.systopia.committees/blob/master/docs/index.md

**Comment by privaterra** [comment]
Yes, let's have chat (via email or signal?) !

I've been maintaining a database in CiviCRM of Congressional members (house & senate), committees, and their staff. It's been a pretty manual process, and a more sophisticated solution, such as using a module to pull in the data would be much better, easier, and less prone to errors.  Would be great to coordinate with you and perhaps others to get your code to also work with the existing (free/open) congressional data that is available.

As for the data, the source of congressional member & committee information that I am using is the GitHub [US Congress Repository ](https://github.com/unitedstates), specifically the [congress-legislators](https://github.com/unitedstates/congress-legislators) repository. The data is updated quite regularly. However, what's harder to obtain is contact information on and about the employees (also known as staff) of the elected members and committees.

Here are the [congress-legislators](https://github.com/unitedstates/congress-legislators) data sets that I manually (via CSV import) add to my CiviCRM database:

- **legislators-current** - Currently serving Members of Congress.
- **legislators-social-media** - Current social media accounts for Members of Congress.
- **committees-current** - Current committees of the Congress, with subcommittees.
- **committee-membership-current** - Current committee/subcommittee assignments.

As I mentioned at the start, really interested in scheduling a call. I'm in Toronto, so some 6 hrs behind you I believe...

looking forward to hearing from you!

Robert

**Comment by bjendres** [comment]
I'm pretty jealous of this repo, as far as I know we don't have anything _that_ comprehensive in Germany.

I'd really be happy for our framework to be used for more scenarios, so I'd suggest to have a brief video call to give you a quick overview and see what's feasible. Feel free to drop me an email at ``endres at systopia.de``.

**Comment by bjendres** [comment]
closed due to inactivity
